# db/seeds/example_sentence.rb
ExampleSentence.find_or_create_by!(sentence: 'これはペンです。', sentence_html: '<ruby>これは<rt>kore wa</rt></ruby>ペンです。') { |e| e.translation = 'This is a pen.' }
ExampleSentence.find_or_create_by!(sentence: '私は学生です。', sentence_html: '<ruby>私は<rt>watashi wa</rt></ruby>学生です。') { |e| e.translation = 'I am a student.' }
ExampleSentence.find_or_create_by!(sentence: '猫が好きです。', sentence_html: '<ruby>猫<rt>neko</rt></ruby>が好きです。') { |e| e.translation = 'I like cats.' }
ExampleSentence.find_or_create_by!(sentence: '水を飲みます。', sentence_html: '<ruby>水<rt>mizu</rt></ruby>を飲みます。') { |e| e.translation = 'I drink water.' }
ExampleSentence.find_or_create_by!(sentence: '毎日勉強します。', sentence_html: '<ruby>毎日<rt>mainichi</rt></ruby>勉強します。') { |e| e.translation = 'I study every day.' }
ExampleSentence.find_or_create_by!(sentence: '友達と話します。', sentence_html: '<ruby>友達<rt>tomodachi</rt></ruby>と話します。') { |e| e.translation = 'I talk with my friends.' }
ExampleSentence.find_or_create_by!(sentence: '朝ごはんを食べました。', sentence_html: '<ruby>朝ごはん<rt>asagohan</rt></ruby>を食べました。') { |e| e.translation = 'I ate breakfast.' }
ExampleSentence.find_or_create_by!(sentence: '昨日映画を見ました。', sentence_html: '<ruby>昨日<rt>kinou</rt></ruby>映画を見ました。') { |e| e.translation = 'I watched a movie yesterday.' }
ExampleSentence.find_or_create_by!(sentence: '本を読みます。', sentence_html: '<ruby>本<rt>hon</rt></ruby>を読みます。') { |e| e.translation = 'I read books.' }
ExampleSentence.find_or_create_by!(sentence: '音楽を聞きます。', sentence_html: '<ruby>音楽<rt>ongaku</rt></ruby>を聞きます。') { |e| e.translation = 'I listen to music.' }
ExampleSentence.find_or_create_by!(sentence: '車で行きます。', sentence_html: '<ruby>車<rt>kuruma</rt></ruby>で行きます。') { |e| e.translation = 'I go by car.' }
ExampleSentence.find_or_create_by!(sentence: '駅で待ちます。', sentence_html: '<ruby>駅<rt>eki</rt></ruby>で待ちます。') { |e| e.translation = 'I wait at the station.' }
ExampleSentence.find_or_create_by!(sentence: '雨が降っています。', sentence_html: '<ruby>雨<rt>ame</rt></ruby>が降っています。') { |e| e.translation = 'It is raining.' }
ExampleSentence.find_or_create_by!(sentence: '山に登ります。', sentence_html: '<ruby>山<rt>yama</rt></ruby>に登ります。') { |e| e.translation = 'I climb mountains.' }
ExampleSentence.find_or_create_by!(sentence: '海で泳ぎます。', sentence_html: '<ruby>海<rt>umi</rt></ruby>で泳ぎます。') { |e| e.translation = 'I swim in the sea.' }
ExampleSentence.find_or_create_by!(sentence: '公園で遊びます。', sentence_html: '<ruby>公園<rt>kouen</rt></ruby>で遊びます。') { |e| e.translation = 'I play in the park.' }
ExampleSentence.find_or_create_by!(sentence: '家に帰ります。', sentence_html: '<ruby>家<rt>ie</rt></ruby>に帰ります。') { |e| e.translation = 'I go home.' }
ExampleSentence.find_or_create_by!(sentence: '犬を飼っています。', sentence_html: '<ruby>犬<rt>inu</rt></ruby>を飼っています。') { |e| e.translation = 'I have a dog.' }
ExampleSentence.find_or_create_by!(sentence: '花が咲いています。', sentence_html: '<ruby>花<rt>hana</rt></ruby>が咲いています。') { |e| e.translation = 'Flowers are blooming.' }
ExampleSentence.find_or_create_by!(sentence: '手紙を書きます。', sentence_html: '<ruby>手紙<rt>tegami</rt></ruby>を書きます。') { |e| e.translation = 'I write a letter.' }
ExampleSentence.find_or_create_by!(sentence: '写真を撮ります。', sentence_html: '<ruby>写真<rt>shashin</rt></ruby>を撮ります。') { |e| e.translation = 'I take a photo.' }
ExampleSentence.find_or_create_by!(sentence: '電話をかけます。', sentence_html: '<ruby>電話<rt>denwa</rt></ruby>をかけます。') { |e| e.translation = 'I make a phone call.' }
ExampleSentence.find_or_create_by!(sentence: '料理を作ります。', sentence_html: '<ruby>料理<rt>ryouri</rt></ruby>を作ります。') { |e| e.translation = 'I cook food.' }
ExampleSentence.find_or_create_by!(sentence: '英語を勉強します。', sentence_html: '<ruby>英語<rt>eigo</rt></ruby>を勉強します。') { |e| e.translation = 'I study English.' }
ExampleSentence.find_or_create_by!(sentence: '日本語を話します。', sentence_html: '<ruby>日本語<rt>nihongo</rt></ruby>を話します。') { |e| e.translation = 'I speak Japanese.' }
ExampleSentence.find_or_create_by!(sentence: '新しい靴を買いました。', sentence_html: '<ruby>新しい<rt>atarashii</rt></ruby>靴を買いました。') { |e| e.translation = 'I bought new shoes.' }
ExampleSentence.find_or_create_by!(sentence: '古い本を読みます。', sentence_html: '<ruby>古い<rt>furui</rt></ruby>本を読みます。') { |e| e.translation = 'I read an old book.' }
ExampleSentence.find_or_create_by!(sentence: '高い山に登ります。', sentence_html: '<ruby>高い<rt>takai</rt></ruby>山に登ります。') { |e| e.translation = 'I climb a tall mountain.' }
ExampleSentence.find_or_create_by!(sentence: '低い声で話します。', sentence_html: '<ruby>低い<rt>hikui</rt></ruby>声で話します。') { |e| e.translation = 'I speak in a low voice.' }
ExampleSentence.find_or_create_by!(sentence: '速く走ります。', sentence_html: '<ruby>速く<rt>hayaku</rt></ruby>走ります。') { |e| e.translation = 'I run fast.' }
ExampleSentence.find_or_create_by!(sentence: '遅く起きました。', sentence_html: '<ruby>遅く<rt>osoku</rt></ruby>起きました。') { |e| e.translation = 'I woke up late.' }
ExampleSentence.find_or_create_by!(sentence: '広い部屋です。', sentence_html: '<ruby>広い<rt>hiroi</rt></ruby>部屋です。') { |e| e.translation = 'It is a spacious room.' }
ExampleSentence.find_or_create_by!(sentence: '狭い道を歩きます。', sentence_html: '<ruby>狭い<rt>semai</rt></ruby>道を歩きます。') { |e| e.translation = 'I walk on a narrow road.' }
ExampleSentence.find_or_create_by!(sentence: '明るい部屋です。', sentence_html: '<ruby>明るい<rt>akarui</rt></ruby>部屋です。') { |e| e.translation = 'It is a bright room.' }
ExampleSentence.find_or_create_by!(sentence: '暗い夜です。', sentence_html: '<ruby>暗い<rt>kurai</rt></ruby>夜です。') { |e| e.translation = 'It is a dark night.' }
ExampleSentence.find_or_create_by!(sentence: '強い風が吹いています。', sentence_html: '<ruby>強い<rt>tsuyoi</rt></ruby>風が吹いています。') { |e| e.translation = 'A strong wind is blowing.' }
ExampleSentence.find_or_create_by!(sentence: '弱い雨が降っています。', sentence_html: '<ruby>弱い<rt>yowai</rt></ruby>雨が降っています。') { |e| e.translation = 'A light rain is falling.' }
ExampleSentence.find_or_create_by!(sentence: '長い道のりです。', sentence_html: '<ruby>長い<rt>nagai</rt></ruby>道のりです。') { |e| e.translation = 'It is a long journey.' }
ExampleSentence.find_or_create_by!(sentence: '短い手紙を書きます。', sentence_html: '<ruby>短い<rt>mijikai</rt></ruby>手紙を書きます。') { |e| e.translation = 'I write a short letter.' }
ExampleSentence.find_or_create_by!(sentence: '重い荷物を持ちます。', sentence_html: '<ruby>重い<rt>omoi</rt></ruby>荷物を持ちます。') { |e| e.translation = 'I carry a heavy bag.' }
ExampleSentence.find_or_create_by!(sentence: '軽いかばんです。', sentence_html: '<ruby>軽い<rt>karui</rt></ruby>かばんです。') { |e| e.translation = 'It is a light bag.' }
ExampleSentence.find_or_create_by!(sentence: '暑い日です。', sentence_html: '<ruby>暑い<rt>atsui</rt></ruby>日です。') { |e| e.translation = 'It is a hot day.' }
ExampleSentence.find_or_create_by!(sentence: '寒い冬です。', sentence_html: '<ruby>寒い<rt>samui</rt></ruby>冬です。') { |e| e.translation = 'It is a cold winter.' }
ExampleSentence.find_or_create_by!(sentence: '新しい友達ができました。', sentence_html: '<ruby>新しい<rt>atarashii</rt></ruby>友達ができました。') { |e| e.translation = 'I made a new friend.' }
ExampleSentence.find_or_create_by!(sentence: '古い写真を見ます。', sentence_html: '<ruby>古い<rt>furui</rt></ruby>写真を見ます。') { |e| e.translation = 'I look at an old photo.' }
ExampleSentence.find_or_create_by!(sentence: '青い空です。', sentence_html: '<ruby>青い<rt>aoi</rt></ruby>空です。') { |e| e.translation = 'The sky is blue.' }
ExampleSentence.find_or_create_by!(sentence: '赤い花が咲いています。', sentence_html: '<ruby>赤い<rt>akai</rt></ruby>花が咲いています。') { |e| e.translation = 'Red flowers are blooming.' }
ExampleSentence.find_or_create_by!(sentence: '白い犬がいます。', sentence_html: '<ruby>白い<rt>shiroi</rt></ruby>犬がいます。') { |e| e.translation = 'There is a white dog.' }
ExampleSentence.find_or_create_by!(sentence: '黒い猫がいます。', sentence_html: '<ruby>黒い<rt>kuroi</rt></ruby>猫がいます。') { |e| e.translation = 'There is a black cat.' }