# db/seeds/grammar.rb
Grammar.create!(title: 'は', slug: 'wa', meanings: ['Topic marker'])
Grammar.create!(title: 'が', slug: 'ga', meanings: ['Subject marker'])
Grammar.create!(title: 'を', slug: 'wo', meanings: ['Object marker'])
Grammar.create!(title: 'に', slug: 'ni', meanings: ['Direction/time marker'])
Grammar.create!(title: 'で', slug: 'de', meanings: ['Location marker'])
Grammar.create!(title: 'の', slug: 'no', meanings: ['Possessive marker'])
Grammar.create!(title: 'と', slug: 'to', meanings: ['And/with'])
Grammar.create!(title: 'も', slug: 'mo', meanings: ['Also/too'])
Grammar.create!(title: 'から', slug: 'kara', meanings: ['From/since'])
Grammar.create!(title: 'まで', slug: 'made', meanings: ['Until/up to'])
Grammar.create!(title: 'より', slug: 'yori', meanings: ['Than (comparison)'])
Grammar.create!(title: 'だけ', slug: 'dake', meanings: ['Only/just'])
Grammar.create!(title: 'しか', slug: 'shika', meanings: ['Only (with negative)'])
Grammar.create!(title: 'でも', slug: 'demo', meanings: ['But/however'])
Grammar.create!(title: 'ので', slug: 'node', meanings: ['Because (reason)'])
Grammar.create!(title: 'けど', slug: 'kedo', meanings: ['But/although'])
Grammar.create!(title: 'ながら', slug: 'nagara', meanings: ['While doing'])
Grammar.create!(title: 'たり', slug: 'tari', meanings: ['Listing actions'])
Grammar.create!(title: 'たり...たり', slug: 'tari-tari', meanings: ['Doing things like...'])
Grammar.create!(title: 'そう', slug: 'sou', meanings: ['Looks like/seems'])
Grammar.create!(title: 'よう', slug: 'you', meanings: ['Like/as if'])
Grammar.create!(title: 'みたい', slug: 'mitai', meanings: ['Like/similar to'])
Grammar.create!(title: 'こと', slug: 'koto', meanings: ['Nominalizer'])
Grammar.create!(title: 'のに', slug: 'noni', meanings: ['Despite/although'])
Grammar.create!(title: 'ため', slug: 'tame', meanings: ['For/because of'])
Grammar.create!(title: 'つもり', slug: 'tsumori', meanings: ['Intend to'])
Grammar.create!(title: 'はず', slug: 'hazu', meanings: ['Should/expected to'])
Grammar.create!(title: 'べき', slug: 'beki', meanings: ['Should/ought to'])
Grammar.create!(title: 'ことができる', slug: 'kotogadekiru', meanings: ['Can do'])
Grammar.create!(title: 'ことになる', slug: 'kotoninaru', meanings: ['It has been decided that'])
Grammar.create!(title: 'ことにする', slug: 'kotonisuru', meanings: ['Decide to'])
Grammar.create!(title: 'ている', slug: 'teiru', meanings: ['Ongoing action'])
Grammar.create!(title: 'てある', slug: 'tearu', meanings: ['Resulting state'])
Grammar.create!(title: 'てみる', slug: 'temiru', meanings: ['Try doing'])
Grammar.create!(title: 'てしまう', slug: 'teshimau', meanings: ['Finish doing'])
Grammar.create!(title: 'ておく', slug: 'teoku', meanings: ['Do in advance'])
Grammar.create!(title: 'てもいい', slug: 'temoii', meanings: ['May/is allowed'])
Grammar.create!(title: 'てはいけない', slug: 'tewaikenai', meanings: ['Must not'])
Grammar.create!(title: 'なくてもいい', slug: 'nakutemoii', meanings: ['Don\'t have to'])
Grammar.create!(title: 'なければならない', slug: 'nakerebanaranai', meanings: ['Must/have to'])
Grammar.create!(title: 'なくてはいけない', slug: 'nakutewaikenai', meanings: ['Must/have to'])
Grammar.create!(title: 'でしょう', slug: 'deshou', meanings: ['Probably'])
Grammar.create!(title: 'かもしれない', slug: 'kamoshirenai', meanings: ['Might/perhaps'])
Grammar.create!(title: 'らしい', slug: 'rashii', meanings: ['Apparently'])
Grammar.create!(title: 'そうだ', slug: 'souda', meanings: ['I heard that'])
Grammar.create!(title: 'ようだ', slug: 'youda', meanings: ['It seems that'])
Grammar.create!(title: 'ばかり', slug: 'bakari', meanings: ['Just did'])
Grammar.create!(title: 'ばかりだ', slug: 'bakarida', meanings: ['Keep doing'])
Grammar.create!(title: 'ばかりに', slug: 'bakarini', meanings: ['Just because'])
Grammar.create!(title: 'てくる', slug: 'tekuru', meanings: ['To come to do (change or movement toward speaker)'])
