# db/seeds/kanji.rb
Kanji.create!(title: '愛', slug: 'ai', meanings: ['love'], kunyomi_readings: ['あい'], onyomi_readings: ['アイ'])
Kanji.create!(title: '力', slug: 'chikara', meanings: ['power'], kunyomi_readings: ['ちから'], onyomi_readings: ['リョク'])
Kanji.create!(title: '水', slug: 'mizu', meanings: ['water'], kunyomi_readings: ['みず'], onyomi_readings: ['スイ'])
Kanji.create!(title: '火', slug: 'hi', meanings: ['fire'], kunyomi_readings: ['ひ'], onyomi_readings: ['カ'])
Kanji.create!(title: '木', slug: 'ki', meanings: ['tree'], kunyomi_readings: ['き'], onyomi_readings: ['モク'])
Kanji.create!(title: '金', slug: 'kane', meanings: ['gold', 'money'], kunyomi_readings: ['かね'], onyomi_readings: ['キン'])
Kanji.create!(title: '土', slug: 'tsuchi', meanings: ['earth', 'soil'], kunyomi_readings: ['つち'], onyomi_readings: ['ド'])
Kanji.create!(title: '空', slug: 'sora', meanings: ['sky', 'empty'], kunyomi_readings: ['そら'], onyomi_readings: ['クウ'])
Kanji.create!(title: '山', slug: 'yama', meanings: ['mountain'], kunyomi_readings: ['やま'], onyomi_readings: ['サン'])
Kanji.create!(title: '川', slug: 'kawa', meanings: ['river'], kunyomi_readings: ['かわ'], onyomi_readings: ['セン'])
Kanji.create!(title: '田', slug: 'ta', meanings: ['rice field'], kunyomi_readings: ['た'], onyomi_readings: ['デン'])
Kanji.create!(title: '人', slug: 'hito', meanings: ['person'], kunyomi_readings: ['ひと'], onyomi_readings: ['ジン', 'ニン'])
Kanji.create!(title: '女', slug: 'onna', meanings: ['woman'], kunyomi_readings: ['おんな'], onyomi_readings: ['ジョ'])
Kanji.create!(title: '男', slug: 'otoko', meanings: ['man'], kunyomi_readings: ['おとこ'], onyomi_readings: ['ダン'])
Kanji.create!(title: '子', slug: 'ko', meanings: ['child'], kunyomi_readings: ['こ'], onyomi_readings: ['シ'])
Kanji.create!(title: '日', slug: 'hi2', meanings: ['day', 'sun'], kunyomi_readings: ['ひ'], onyomi_readings: ['ニチ', 'ジツ'])
Kanji.create!(title: '月', slug: 'tsuki', meanings: ['moon', 'month'], kunyomi_readings: ['つき'], onyomi_readings: ['ゲツ', 'ガツ'])
Kanji.create!(title: '年', slug: 'toshi', meanings: ['year'], kunyomi_readings: ['とし'], onyomi_readings: ['ネン'])
Kanji.create!(title: '時', slug: 'toki', meanings: ['time', 'hour'], kunyomi_readings: ['とき'], onyomi_readings: ['ジ'])
Kanji.create!(title: '分', slug: 'fun', meanings: ['minute', 'part'], kunyomi_readings: ['わ'], onyomi_readings: ['ブン', 'フン'])
Kanji.create!(title: '先', slug: 'saki', meanings: ['ahead', 'previous'], kunyomi_readings: ['さき'], onyomi_readings: ['セン'])
Kanji.create!(title: '生', slug: 'sei', meanings: ['life', 'birth'], kunyomi_readings: ['いきる', 'うまれる'], onyomi_readings: ['セイ', 'ショウ'])
Kanji.create!(title: '学', slug: 'gaku', meanings: ['study', 'learning'], kunyomi_readings: ['まなぶ'], onyomi_readings: ['ガク'])
Kanji.create!(title: '校', slug: 'kou', meanings: ['school'], kunyomi_readings: ['こう'], onyomi_readings: ['コウ'])
Kanji.create!(title: '友', slug: 'tomo', meanings: ['friend'], kunyomi_readings: ['とも'], onyomi_readings: ['ユウ'])
Kanji.create!(title: '本', slug: 'hon', meanings: ['book', 'origin'], kunyomi_readings: ['もと'], onyomi_readings: ['ホン'])
Kanji.create!(title: '語', slug: 'go', meanings: ['language', 'word'], kunyomi_readings: ['かたる'], onyomi_readings: ['ゴ'])
Kanji.create!(title: '話', slug: 'hanashi', meanings: ['talk', 'story'], kunyomi_readings: ['はなす'], onyomi_readings: ['ワ'])
Kanji.create!(title: '聞', slug: 'kiku', meanings: ['hear', 'ask'], kunyomi_readings: ['きく'], onyomi_readings: ['ブン'])
Kanji.create!(title: '見', slug: 'miru', meanings: ['see', 'look'], kunyomi_readings: ['みる'], onyomi_readings: ['ケン'])
Kanji.create!(title: '行', slug: 'iku', meanings: ['go', 'act'], kunyomi_readings: ['いく'], onyomi_readings: ['コウ', 'ギョウ'])
Kanji.create!(title: '来', slug: 'kuru', meanings: ['come'], kunyomi_readings: ['くる'], onyomi_readings: ['ライ'])
Kanji.create!(title: '食', slug: 'taberu', meanings: ['eat'], kunyomi_readings: ['たべる'], onyomi_readings: ['ショク'])
Kanji.create!(title: '飲', slug: 'nomu', meanings: ['drink'], kunyomi_readings: ['のむ'], onyomi_readings: ['イン'])
Kanji.create!(title: '買', slug: 'kau', meanings: ['buy'], kunyomi_readings: ['かう'], onyomi_readings: ['バイ'])
Kanji.create!(title: '書', slug: 'kaku', meanings: ['write'], kunyomi_readings: ['かく'], onyomi_readings: ['ショ'])
Kanji.create!(title: '読', slug: 'yomu', meanings: ['read'], kunyomi_readings: ['よむ'], onyomi_readings: ['ドク'])
Kanji.create!(title: '立', slug: 'tatsu', meanings: ['stand'], kunyomi_readings: ['たつ'], onyomi_readings: ['リツ'])
Kanji.create!(title: '休', slug: 'yasumu', meanings: ['rest'], kunyomi_readings: ['やすむ'], onyomi_readings: ['キュウ'])
Kanji.create!(title: '入', slug: 'hairu', meanings: ['enter'], kunyomi_readings: ['はいる'], onyomi_readings: ['ニュウ'])
Kanji.create!(title: '出', slug: 'deru', meanings: ['exit'], kunyomi_readings: ['でる'], onyomi_readings: ['シュツ'])
Kanji.create!(title: '会', slug: 'au', meanings: ['meet'], kunyomi_readings: ['あう'], onyomi_readings: ['カイ'])
Kanji.create!(title: '社', slug: 'sha', meanings: ['company', 'shrine'], kunyomi_readings: ['やしろ'], onyomi_readings: ['シャ'])
Kanji.create!(title: '車', slug: 'kuruma', meanings: ['car'], kunyomi_readings: ['くるま'], onyomi_readings: ['シャ'])
Kanji.create!(title: '電', slug: 'den', meanings: ['electricity'], kunyomi_readings: ['でん'], onyomi_readings: ['デン'])
Kanji.create!(title: '駅', slug: 'eki', meanings: ['station'], kunyomi_readings: ['えき'], onyomi_readings: ['エキ'])
Kanji.create!(title: '家', slug: 'ie', meanings: ['house'], kunyomi_readings: ['いえ'], onyomi_readings: ['カ'])
Kanji.create!(title: '音', slug: 'oto', meanings: ['sound'], kunyomi_readings: ['おと'], onyomi_readings: ['オン'])
Kanji.create!(title: '楽', slug: 'raku', meanings: ['comfort', 'music'], kunyomi_readings: ['たのしい'], onyomi_readings: ['ガク', 'ラク'])
Kanji.create!(title: '虎', slug: 'tora', meanings: ['tiger'], kunyomi_readings: ['とら'], onyomi_readings: ['トウ'])