# db/seeds/kanji.rb
Kanji.find_or_create_by!(slug: 'ai', title: '愛', meanings: ['love'], kunyomi_readings: ['あい'], onyomi_readings: ['アイ'])
Kanji.find_or_create_by!(slug: 'chikara', title: '力', meanings: ['power'], kunyomi_readings: ['ちから'], onyomi_readings: ['リョク'])
Kanji.find_or_create_by!(slug: 'mizu', title: '水', meanings: ['water'], kunyomi_readings: ['みず'], onyomi_readings: ['スイ'])
Kanji.find_or_create_by!(slug: 'hi', title: '火', meanings: ['fire'], kunyomi_readings: ['ひ'], onyomi_readings: ['カ'])
Kanji.find_or_create_by!(slug: 'ki', title: '木', meanings: ['tree'], kunyomi_readings: ['き'], onyomi_readings: ['モク'])
Kanji.find_or_create_by!(slug: 'kane', title: '金', meanings: ['gold', 'money'], kunyomi_readings: ['かね'], onyomi_readings: ['キン'])
Kanji.find_or_create_by!(slug: 'tsuchi', title: '土', meanings: ['earth', 'soil'], kunyomi_readings: ['つち'], onyomi_readings: ['ド'])
Kanji.find_or_create_by!(slug: 'sora', title: '空', meanings: ['sky', 'empty'], kunyomi_readings: ['そら'], onyomi_readings: ['クウ'])
Kanji.find_or_create_by!(slug: 'yama', title: '山', meanings: ['mountain'], kunyomi_readings: ['やま'], onyomi_readings: ['サン'])
Kanji.find_or_create_by!(slug: 'kawa', title: '川', meanings: ['river'], kunyomi_readings: ['かわ'], onyomi_readings: ['セン'])
Kanji.find_or_create_by!(slug: 'ta', title: '田', meanings: ['rice field'], kunyomi_readings: ['た'], onyomi_readings: ['デン'])
Kanji.find_or_create_by!(slug: 'hito', title: '人', meanings: ['person'], kunyomi_readings: ['ひと'], onyomi_readings: ['ジン', 'ニン'])
Kanji.find_or_create_by!(slug: 'onna', title: '女', meanings: ['woman'], kunyomi_readings: ['おんな'], onyomi_readings: ['ジョ'])
Kanji.find_or_create_by!(slug: 'otoko', title: '男', meanings: ['man'], kunyomi_readings: ['おとこ'], onyomi_readings: ['ダン'])
Kanji.find_or_create_by!(slug: 'ko', title: '子', meanings: ['child'], kunyomi_readings: ['こ'], onyomi_readings: ['シ'])
Kanji.find_or_create_by!(slug: 'hi2', title: '日', meanings: ['day', 'sun'], kunyomi_readings: ['ひ'], onyomi_readings: ['ニチ', 'ジツ'])
Kanji.find_or_create_by!(slug: 'tsuki', title: '月', meanings: ['moon', 'month'], kunyomi_readings: ['つき'], onyomi_readings: ['ゲツ', 'ガツ'])
Kanji.find_or_create_by!(slug: 'toshi', title: '年', meanings: ['year'], kunyomi_readings: ['とし'], onyomi_readings: ['ネン'])
Kanji.find_or_create_by!(slug: 'toki', title: '時', meanings: ['time', 'hour'], kunyomi_readings: ['とき'], onyomi_readings: ['ジ'])
Kanji.find_or_create_by!(slug: 'fun', title: '分', meanings: ['minute', 'part'], kunyomi_readings: ['わ'], onyomi_readings: ['ブン', 'フン'])
Kanji.find_or_create_by!(slug: 'saki', title: '先', meanings: ['ahead', 'previous'], kunyomi_readings: ['さき'], onyomi_readings: ['セン'])
Kanji.find_or_create_by!(slug: 'sei', title: '生', meanings: ['life', 'birth'], kunyomi_readings: ['いきる', 'うまれる'], onyomi_readings: ['セイ', 'ショウ'])
Kanji.find_or_create_by!(slug: 'gaku', title: '学', meanings: ['study', 'learning'], kunyomi_readings: ['まなぶ'], onyomi_readings: ['ガク'])
Kanji.find_or_create_by!(slug: 'kou', title: '校', meanings: ['school'], kunyomi_readings: ['こう'], onyomi_readings: ['コウ'])
Kanji.find_or_create_by!(slug: 'tomo', title: '友', meanings: ['friend'], kunyomi_readings: ['とも'], onyomi_readings: ['ユウ'])
Kanji.find_or_create_by!(slug: 'hon', title: '本', meanings: ['book', 'origin'], kunyomi_readings: ['もと'], onyomi_readings: ['ホン'])
Kanji.find_or_create_by!(slug: 'go', title: '語', meanings: ['language', 'word'], kunyomi_readings: ['かたる'], onyomi_readings: ['ゴ'])
Kanji.find_or_create_by!(slug: 'hanashi', title: '話', meanings: ['talk', 'story'], kunyomi_readings: ['はなす'], onyomi_readings: ['ワ'])
Kanji.find_or_create_by!(slug: 'kiku', title: '聞', meanings: ['hear', 'ask'], kunyomi_readings: ['きく'], onyomi_readings: ['ブン'])
Kanji.find_or_create_by!(slug: 'miru', title: '見', meanings: ['see', 'look'], kunyomi_readings: ['みる'], onyomi_readings: ['ケン'])
Kanji.find_or_create_by!(slug: 'iku', title: '行', meanings: ['go', 'act'], kunyomi_readings: ['いく'], onyomi_readings: ['コウ', 'ギョウ'])
Kanji.find_or_create_by!(slug: 'kuru', title: '来', meanings: ['come'], kunyomi_readings: ['くる'], onyomi_readings: ['ライ'])
Kanji.find_or_create_by!(slug: 'taberu', title: '食', meanings: ['eat'], kunyomi_readings: ['たべる'], onyomi_readings: ['ショク'])
Kanji.find_or_create_by!(slug: 'nomu', title: '飲', meanings: ['drink'], kunyomi_readings: ['のむ'], onyomi_readings: ['イン'])
Kanji.find_or_create_by!(slug: 'kau', title: '買', meanings: ['buy'], kunyomi_readings: ['かう'], onyomi_readings: ['バイ'])
Kanji.find_or_create_by!(slug: 'kaku', title: '書', meanings: ['write'], kunyomi_readings: ['かく'], onyomi_readings: ['ショ'])
Kanji.find_or_create_by!(slug: 'yomu', title: '読', meanings: ['read'], kunyomi_readings: ['よむ'], onyomi_readings: ['ドク'])
Kanji.find_or_create_by!(slug: 'tatsu', title: '立', meanings: ['stand'], kunyomi_readings: ['たつ'], onyomi_readings: ['リツ'])
Kanji.find_or_create_by!(slug: 'yasumu', title: '休', meanings: ['rest'], kunyomi_readings: ['やすむ'], onyomi_readings: ['キュウ'])
Kanji.find_or_create_by!(slug: 'hairu', title: '入', meanings: ['enter'], kunyomi_readings: ['はいる'], onyomi_readings: ['ニュウ'])
Kanji.find_or_create_by!(slug: 'deru', title: '出', meanings: ['exit'], kunyomi_readings: ['でる'], onyomi_readings: ['シュツ'])
Kanji.find_or_create_by!(slug: 'au', title: '会', meanings: ['meet'], kunyomi_readings: ['あう'], onyomi_readings: ['カイ'])
Kanji.find_or_create_by!(slug: 'sha', title: '社', meanings: ['company', 'shrine'], kunyomi_readings: ['やしろ'], onyomi_readings: ['シャ'])
Kanji.find_or_create_by!(slug: 'kuruma', title: '車', meanings: ['car'], kunyomi_readings: ['くるま'], onyomi_readings: ['シャ'])
Kanji.find_or_create_by!(slug: 'den', title: '電', meanings: ['electricity'], kunyomi_readings: ['でん'], onyomi_readings: ['デン'])
Kanji.find_or_create_by!(slug: 'eki', title: '駅', meanings: ['station'], kunyomi_readings: ['えき'], onyomi_readings: ['エキ'])
Kanji.find_or_create_by!(slug: 'ie', title: '家', meanings: ['house'], kunyomi_readings: ['いえ'], onyomi_readings: ['カ'])
Kanji.find_or_create_by!(slug: 'oto', title: '音', meanings: ['sound'], kunyomi_readings: ['おと'], onyomi_readings: ['オン'])
Kanji.find_or_create_by!(slug: 'raku', title: '楽', meanings: ['comfort', 'music'], kunyomi_readings: ['たのしい'], onyomi_readings: ['ガク', 'ラク'])
Kanji.find_or_create_by!(slug: 'tora', title: '虎', meanings: ['tiger'], kunyomi_readings: ['とら'], onyomi_readings: ['トウ'])